# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d7a07bc4eb29eb84676d8f51d204f1e1fdc454513e35854bafcf7d0acef37d08241d864921b36bdd4ee4ab234606a617ed053a6a11497e12f5eee142f67560e

test:
  secret_key_base: d8afc1e88c06937c57596d35ce9cd4a422c24db2b2079ad7475071d674a597b461f590abec2c8516c3a701a4c35a8ea25957f4a6f8f7eb19ffc292111bd1660f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
